#!/usr/bin/env python3
"""Generate synthetic migration scenario data for Demo Rivers Health secondment demo."""

from __future__ import annotations

import csv
from pathlib import Path

from mhsds_source_report_data import (
    MAP_COLS,
    build_episodes,
    build_source_to_report_map,
    build_submission_artifacts,
)

RANDOM_SEED = 42
GENERATOR_VERSION = "1.0.0"
TRUST_ODS = "DRH"
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR.parent / "data"
REGENERATE_CMD = "python3 site/secondment-demo/generator/create_migration_scenario_data.py"
ANCHOR_PATIENT = "DRH-PAT-002896"


def write_csv(name: str, fieldnames: list[str], rows: list[dict]) -> int:
    path = DATA_DIR / name
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        w.writerows(rows)
    return len(rows)


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    legendary = [
        {"CaseId": "Case LC-10001", "PatientPseudoId": ANCHOR_PATIENT, "ReferralDate": "2025-12-08",
         "PathwayStatus": "Rejected", "PathwayStartDate": "2025-12-08", "FirstContactDate": "",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-N", "ReportingMonth": "2025-12",
         "OutcomeText": "Wrong service", "ContactCount": "0", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10002", "PatientPseudoId": "DRH-PAT-001104", "ReferralDate": "2025-12-15",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-01-03", "FirstContactDate": "2026-01-10",
         "ClosureDate": "2026-03-20", "ResponsibleTeam": "CMHT-S", "ReportingMonth": "2026-01",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10003", "PatientPseudoId": "DRH-PAT-001552", "ReferralDate": "2026-01-05",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-01-05", "FirstContactDate": "2026-01-17",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-E", "ReportingMonth": "2026-01",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10004", "PatientPseudoId": "DRH-PAT-003201", "ReferralDate": "2026-02-10",
         "PathwayStatus": "InTreatment", "PathwayStartDate": "2026-02-12", "FirstContactDate": "2026-02-20",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-N", "ReportingMonth": "2026-02",
         "OutcomeText": "", "ContactCount": "3", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10005", "PatientPseudoId": "DRH-PAT-000874", "ReferralDate": "2026-02-18",
         "PathwayStatus": "Waiting", "PathwayStartDate": "2026-02-18", "FirstContactDate": "",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-N", "ReportingMonth": "2026-02",
         "OutcomeText": "", "ContactCount": "0", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10006", "PatientPseudoId": "DRH-PAT-004210", "ReferralDate": "2026-01-22",
         "PathwayStatus": "Rejected", "PathwayStartDate": "2026-01-22", "FirstContactDate": "",
         "ClosureDate": "", "ResponsibleTeam": "CRHT", "ReportingMonth": "2026-01",
         "OutcomeText": "Not appropriate", "ContactCount": "0", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10007", "PatientPseudoId": "DRH-PAT-005663", "ReferralDate": "2026-02-05",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-02-08", "FirstContactDate": "2026-02-15",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-S", "ReportingMonth": "2026-02",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10008", "PatientPseudoId": "DRH-PAT-002370", "ReferralDate": "2026-03-01",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-03-04", "FirstContactDate": "2026-03-11",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-N", "ReportingMonth": "2026-03",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10009", "PatientPseudoId": "DRH-PAT-003907", "ReferralDate": "2026-01-12",
         "PathwayStatus": "Waiting", "PathwayStartDate": "2026-01-12", "FirstContactDate": "",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-E", "ReportingMonth": "2026-01",
         "OutcomeText": "", "ContactCount": "0", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10010", "PatientPseudoId": "DRH-PAT-002575", "ReferralDate": "2026-02-20",
         "PathwayStatus": "InTreatment", "PathwayStartDate": "2026-02-22", "FirstContactDate": "2026-03-01",
         "ClosureDate": "", "ResponsibleTeam": "AA-MH-NORTH-01", "ReportingMonth": "2026-02",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10011", "PatientPseudoId": "DRH-PAT-000237", "ReferralDate": "2025-11-20",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2025-11-25", "FirstContactDate": "2025-12-02",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-N", "ReportingMonth": "2025-11",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10012", "PatientPseudoId": "DRH-PAT-003493", "ReferralDate": "2026-03-05",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-03-07", "FirstContactDate": "2026-03-14",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-S", "ReportingMonth": "2026-03",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10013", "PatientPseudoId": "DRH-PAT-002569", "ReferralDate": "2025-12-28",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-01-08", "FirstContactDate": "2026-01-15",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-E", "ReportingMonth": "2026-01",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10014", "PatientPseudoId": "DRH-PAT-004563", "ReferralDate": "2026-02-14",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-02-16", "FirstContactDate": "2026-02-23",
         "ClosureDate": "", "ResponsibleTeam": "PC-LIAISON", "ReportingMonth": "2026-02",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10015", "PatientPseudoId": "DRH-PAT-003520", "ReferralDate": "2026-01-18",
         "PathwayStatus": "Accepted", "PathwayStartDate": "2026-01-20", "FirstContactDate": "2026-01-27",
         "ClosureDate": "2026-03-10", "ResponsibleTeam": "CMHT-N", "ReportingMonth": "2026-01",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10016", "PatientPseudoId": "DRH-PAT-002596", "ReferralDate": "2026-02-25",
         "PathwayStatus": "InTreatment", "PathwayStartDate": "2026-02-27", "FirstContactDate": "2026-03-06",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-S", "ReportingMonth": "2026-03",
         "OutcomeText": "", "ContactCount": "2", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10017", "PatientPseudoId": "DRH-PAT-000667", "ReferralDate": "2026-01-08",
         "PathwayStatus": "Closed", "PathwayStartDate": "2026-01-10", "FirstContactDate": "2026-01-17",
         "ClosureDate": "2026-03-25", "ResponsibleTeam": "CRHT", "ReportingMonth": "2026-01",
         "OutcomeText": "Recovered", "ContactCount": "3", "SourceSystem": "LegendaryCare"},
        {"CaseId": "Case LC-10018", "PatientPseudoId": "DRH-PAT-001890", "ReferralDate": "2026-03-12",
         "PathwayStatus": "Waiting", "PathwayStartDate": "2026-03-12", "FirstContactDate": "",
         "ClosureDate": "", "ResponsibleTeam": "CMHT-N", "ReportingMonth": "2026-03",
         "OutcomeText": "", "ContactCount": "0", "SourceSystem": "LegendaryCare"},
    ]
    lc_fields = list(legendary[0].keys())
    write_csv("legendary_cmht_cases.csv", lc_fields, legendary)

    actions = [
        {"ActionId": "ACT-90001", "PatientPseudoId": ANCHOR_PATIENT, "ActionType": "ACCESS_REJECTED",
         "ActionDate": "2025-12-08", "RejectionReason": "CLINICAL_TRIAGE", "TeamCode": "CMHT-N",
         "Notes": "Excluded from referral count unless triage", "IncludeInReferralCount_NewDefault": "0"},
        {"ActionId": "ACT-90002", "PatientPseudoId": "DRH-PAT-001104", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2025-12-15", "RejectionReason": "", "TeamCode": "AA-MH-SOUTH-01",
         "Notes": "Parallel duplicate risk", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90003", "PatientPseudoId": "DRH-PAT-001104", "ActionType": "CARE_FIRST_CONTACT",
         "ActionDate": "2026-01-03", "RejectionReason": "", "TeamCode": "AA-MH-SOUTH-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90004", "PatientPseudoId": "DRH-PAT-001552", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2026-01-05", "RejectionReason": "", "TeamCode": "AA-MH-EAST-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90005", "PatientPseudoId": "DRH-PAT-001552", "ActionType": "CARE_FIRST_CONTACT",
         "ActionDate": "2026-01-17", "RejectionReason": "", "TeamCode": "AA-MH-EAST-01",
         "Notes": "12 days after access accepted", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90006", "PatientPseudoId": "DRH-PAT-003201", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2026-02-10", "RejectionReason": "", "TeamCode": "AA-MH-NORTH-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90007", "PatientPseudoId": "DRH-PAT-003201", "ActionType": "ADMIN_CANCEL",
         "ActionDate": "2026-02-11", "RejectionReason": "", "TeamCode": "AA-MH-NORTH-01",
         "Notes": "Admin inflate", "IncludeInReferralCount_NewDefault": "0"},
        {"ActionId": "ACT-90008", "PatientPseudoId": "DRH-PAT-003201", "ActionType": "CARE_ONGOING",
         "ActionDate": "2026-02-20", "RejectionReason": "", "TeamCode": "AA-MH-NORTH-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90009", "PatientPseudoId": "DRH-PAT-000874", "ActionType": "ACCESS_WAITING",
         "ActionDate": "2026-02-18", "RejectionReason": "", "TeamCode": "INVALID_TEAM",
         "Notes": "Missing remap", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90010", "PatientPseudoId": "DRH-PAT-004210", "ActionType": "ACCESS_REJECTED",
         "ActionDate": "2026-01-22", "RejectionReason": "NOT_APPROPRIATE", "TeamCode": "AA-CRISIS-01",
         "Notes": "Excluded new count", "IncludeInReferralCount_NewDefault": "0"},
        {"ActionId": "ACT-90011", "PatientPseudoId": "DRH-PAT-005663", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2026-02-05", "RejectionReason": "", "TeamCode": "AA-MH-SOUTH-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90012", "PatientPseudoId": "DRH-PAT-005663", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2026-02-05", "RejectionReason": "", "TeamCode": "AA-MH-SOUTH-01",
         "Notes": "Duplicate action ID pattern", "IncludeInReferralCount_NewDefault": "0"},
        {"ActionId": "ACT-90013", "PatientPseudoId": "DRH-PAT-002370", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2026-03-01", "RejectionReason": "", "TeamCode": "AA-MH-NORTH-01",
         "Notes": "Genuine demand", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90014", "PatientPseudoId": "DRH-PAT-003907", "ActionType": "ACCESS_WAITING",
         "ActionDate": "2026-01-12", "RejectionReason": "", "TeamCode": "AA-MH-EAST-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90015", "PatientPseudoId": "DRH-PAT-002575", "ActionType": "CARE_ONGOING",
         "ActionDate": "2026-03-01", "RejectionReason": "", "TeamCode": "AA-MH-NORTH-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90016", "PatientPseudoId": "DRH-PAT-003493", "ActionType": "CARE_ONGOING",
         "ActionDate": "2026-03-14", "RejectionReason": "", "TeamCode": "AA-MH-SOUTH-01",
         "Notes": "Invalid code X99", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90017", "PatientPseudoId": "DRH-PAT-002569", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2026-01-08", "RejectionReason": "", "TeamCode": "AA-MH-EAST-01",
         "Notes": "Reporting month ambiguity", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90018", "PatientPseudoId": "DRH-PAT-004563", "ActionType": "ACCESS_ACCEPTED",
         "ActionDate": "2026-02-14", "RejectionReason": "", "TeamCode": "AA-PCL-01",
         "Notes": "National yes local no", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90019", "PatientPseudoId": "DRH-PAT-003520", "ActionType": "ADMIN_CANCEL",
         "ActionDate": "2026-01-19", "RejectionReason": "", "TeamCode": "AA-MH-NORTH-01",
         "Notes": "Cancelled duplicate", "IncludeInReferralCount_NewDefault": "0"},
        {"ActionId": "ACT-90020", "PatientPseudoId": "DRH-PAT-002596", "ActionType": "CARE_ONGOING",
         "ActionDate": "2026-03-06", "RejectionReason": "", "TeamCode": "AA-MH-SOUTH-01",
         "Notes": "Missing outcome action", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90021", "PatientPseudoId": "DRH-PAT-000667", "ActionType": "CARE_ONGOING",
         "ActionDate": "2026-03-20", "RejectionReason": "", "TeamCode": "AA-CRISIS-01",
         "Notes": "Open in new, closed in old", "IncludeInReferralCount_NewDefault": "1"},
        {"ActionId": "ACT-90022", "PatientPseudoId": "DRH-PAT-001890", "ActionType": "ACCESS_WAITING",
         "ActionDate": "2026-03-12", "RejectionReason": "", "TeamCode": "AA-MH-NORTH-01",
         "Notes": "", "IncludeInReferralCount_NewDefault": "1"},
    ]
    act_fields = list(actions[0].keys())
    write_csv("pathwayone_actions.csv", act_fields, actions)

    datasets: list[tuple[str, list[str], list[dict]]] = [
        ("feed_cutover_log.csv",
         ["feed_id", "active_from", "active_to", "description", "status"],
         [
             {"feed_id": "legendary_weekly_referral", "active_from": "2025-09-01", "active_to": "2026-01-31",
              "description": "Weekly referral supplement", "status": "Discontinued"},
             {"feed_id": "legendary_nightly_case", "active_from": "2025-09-01", "active_to": "2026-03-31",
              "description": "Nightly case extract", "status": "Full then open-case only"},
             {"feed_id": "legendary_open_case_only", "active_from": "2026-02-01", "active_to": "2026-03-31",
              "description": "Pre-cutover open cases only", "status": "Active"},
             {"feed_id": "pathwayone_api_ingest", "active_from": "2025-11-01", "active_to": "2026-05-31",
              "description": "PathwayOne cloud ingest", "status": "Pilot then primary"},
             {"feed_id": "pathwayone_primary", "active_from": "2026-02-01", "active_to": "2026-05-31",
              "description": "PathwayOne system of record", "status": "Active"},
         ]),
        ("team_service_code_map.csv",
         ["old_team_code", "new_team_code", "team_name", "mapping_status"],
         [
             {"old_team_code": "CMHT-N", "new_team_code": "AA-MH-NORTH-01", "team_name": "Community MH North", "mapping_status": "Active"},
             {"old_team_code": "CMHT-S", "new_team_code": "AA-MH-SOUTH-01", "team_name": "Community MH South", "mapping_status": "Active"},
             {"old_team_code": "CMHT-E", "new_team_code": "AA-MH-EAST-01", "team_name": "Community MH East", "mapping_status": "Active"},
             {"old_team_code": "CRHT", "new_team_code": "AA-CRISIS-01", "team_name": "Crisis Resolution", "mapping_status": "Active"},
             {"old_team_code": "PC-LIAISON", "new_team_code": "AA-PCL-01", "team_name": "Primary Care Liaison", "mapping_status": "Retired Mar 2026"},
         ]),
        ("pathway_status_map.csv",
         ["old_pathway_status", "new_action_type", "action_category", "mapping_note"],
         [
             {"old_pathway_status": "Referred", "new_action_type": "ACCESS_RECEIVED", "action_category": "Access", "mapping_note": "Direct"},
             {"old_pathway_status": "Accepted", "new_action_type": "ACCESS_ACCEPTED", "action_category": "Access", "mapping_note": "Direct"},
             {"old_pathway_status": "Rejected", "new_action_type": "ACCESS_REJECTED", "action_category": "Access", "mapping_note": "Depends on rejection reason"},
             {"old_pathway_status": "Waiting", "new_action_type": "ACCESS_WAITING", "action_category": "Access", "mapping_note": "Many-to-one"},
             {"old_pathway_status": "FirstContact", "new_action_type": "CARE_FIRST_CONTACT", "action_category": "Care", "mapping_note": "Pathway start candidate"},
             {"old_pathway_status": "InTreatment", "new_action_type": "CARE_ONGOING", "action_category": "Care", "mapping_note": "Activity inclusion varies"},
             {"old_pathway_status": "Closed", "new_action_type": "OUTCOME_CLOSED", "action_category": "Outcome", "mapping_note": "Closure event"},
             {"old_pathway_status": "AdminClosure", "new_action_type": "ADMIN_CANCEL", "action_category": "Admin", "mapping_note": "Exclude from clinical counts"},
         ]),
        ("definition_options_referral.csv",
         ["reporting_month", "definition_id", "definition_label", "referral_count", "rule_summary"],
         [
             {"reporting_month": "2026-03", "definition_id": "OPT-A", "definition_label": "Old case referral date", "referral_count": "151", "rule_summary": "Cases with ReferralDate in month"},
             {"reporting_month": "2026-03", "definition_id": "OPT-B", "definition_label": "New access accepted actions", "referral_count": "168", "rule_summary": "ACCESS_ACCEPTED in month"},
             {"reporting_month": "2026-03", "definition_id": "OPT-C", "definition_label": "Agreed hybrid definition", "referral_count": "134", "rule_summary": "Agreed rules with exclusions"},
             {"reporting_month": "2026-03", "definition_id": "DASH", "definition_label": "Dashboard displayed", "referral_count": "154", "rule_summary": "Legacy pipeline +2% vs agreed"},
             {"reporting_month": "2026-01", "definition_id": "OPT-A", "definition_label": "Old case referral date", "referral_count": "156", "rule_summary": "Parallel run"},
             {"reporting_month": "2026-01", "definition_id": "OPT-C", "definition_label": "Agreed hybrid definition", "referral_count": "151", "rule_summary": "Parallel run"},
         ]),
        ("reconciliation_monthly.csv",
         ["reporting_month", "old_case_count", "new_action_count_default", "agreed_definition_count",
          "dashboard_displayed_count", "dashboard_vs_agreed_pct", "migration_phase", "notes"],
         [
             {"reporting_month": "2025-12", "old_case_count": "142", "new_action_count_default": "138",
              "agreed_definition_count": "140", "dashboard_displayed_count": "140", "dashboard_vs_agreed_pct": "0",
              "migration_phase": "B", "notes": "Parallel begins"},
             {"reporting_month": "2026-01", "old_case_count": "156", "new_action_count_default": "149",
              "agreed_definition_count": "151", "dashboard_displayed_count": "151", "dashboard_vs_agreed_pct": "0",
              "migration_phase": "B", "notes": "Dual feed active"},
             {"reporting_month": "2026-02", "old_case_count": "148", "new_action_count_default": "161",
              "agreed_definition_count": "145", "dashboard_displayed_count": "148", "dashboard_vs_agreed_pct": "2.1",
              "migration_phase": "C", "notes": "Referral feed cutover"},
             {"reporting_month": "2026-03", "old_case_count": "151", "new_action_count_default": "168",
              "agreed_definition_count": "134", "dashboard_displayed_count": "154", "dashboard_vs_agreed_pct": "14.9",
              "migration_phase": "D", "notes": "Dashboard +2% narrative; agreed -11%"},
             {"reporting_month": "2026-04", "old_case_count": "147", "new_action_count_default": "155",
              "agreed_definition_count": "143", "dashboard_displayed_count": "143", "dashboard_vs_agreed_pct": "0",
              "migration_phase": "F", "notes": "Legacy extract ended"},
             {"reporting_month": "2026-05", "old_case_count": "152", "new_action_count_default": "158",
              "agreed_definition_count": "149", "dashboard_displayed_count": "149", "dashboard_vs_agreed_pct": "0",
              "migration_phase": "F", "notes": "New only"},
         ]),
        ("migration_risk_register.csv",
         ["risk_id", "risk_description", "owner", "mitigation", "confidence_impact", "status",
          "last_reviewed", "residual_risk", "linked_deliverable"],
         [
             {"risk_id": "R001", "risk_description": "Definition drift during parallel run", "owner": "Performance lead",
              "mitigation": "Facilitate agreed KPI register", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-15", "residual_risk": "High", "linked_deliverable": "kpi-definitions-register"},
             {"risk_id": "R002", "risk_description": "Dashboard refreshes with wrong meaning", "owner": "BI lead",
              "mitigation": "Reconciliation outputs + confidence flags", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-20", "residual_risk": "High", "linked_deliverable": "reporting-assurance-during-migration"},
             {"risk_id": "R003", "risk_description": "Weekly referral feed discontinued Feb", "owner": "IM&T",
              "mitigation": "Feed cutover log + fallback extract", "confidence_impact": "Medium", "status": "Mitigated",
              "last_reviewed": "2026-02-28", "residual_risk": "Low", "linked_deliverable": "reporting-assurance-during-migration"},
             {"risk_id": "R004", "risk_description": "Team code remap incomplete", "owner": "Service manager",
              "mitigation": "Crosswalk validation", "confidence_impact": "Medium", "status": "Open",
              "last_reviewed": "2026-03-10", "residual_risk": "Medium", "linked_deliverable": "reporting-assurance-during-migration"},
             {"risk_id": "R005", "risk_description": "MHSDS-like return uses legacy logic", "owner": "Mandatory reporting owner",
              "mitigation": "Side-by-side test", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-18", "residual_risk": "High", "linked_deliverable": "source-to-report-map"},
             {"risk_id": "R006", "risk_description": "Duplicate actions in PathwayOne", "owner": "BI lead",
              "mitigation": "DQ checks on ActionId", "confidence_impact": "Medium", "status": "Open",
              "last_reviewed": "2026-03-12", "residual_risk": "Medium", "linked_deliverable": "reporting-assurance-during-migration"},
             {"risk_id": "R007", "risk_description": "Phase D spans two source models for Mar reporting", "owner": "Performance lead",
              "mitigation": "Agreed OPT-C hybrid definition", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-22", "residual_risk": "Medium", "linked_deliverable": "definition-migration"},
             {"risk_id": "R008", "risk_description": "Case object no longer exists — pathway logic must be derived", "owner": "BI lead",
              "mitigation": "Episode derivation rules in KPI register", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-16", "residual_risk": "High", "linked_deliverable": "kpi-definitions-register"},
             {"risk_id": "R009", "risk_description": "Rejected referral logic changes between old and new systems", "owner": "Clinical lead",
              "mitigation": "Rejection-reason crosswalk + service sign-off", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-19", "residual_risk": "High", "linked_deliverable": "definition-migration"},
             {"risk_id": "R010", "risk_description": "Pathway start date logic changes (access vs first contact)", "owner": "Service manager",
              "mitigation": "Facilitated KPI-02 definition + vignette testing", "confidence_impact": "Medium", "status": "Open",
              "last_reviewed": "2026-03-14", "residual_risk": "Medium", "linked_deliverable": "kpi-definitions-register"},
             {"risk_id": "R011", "risk_description": "Activity count includes admin actions unless explicitly excluded", "owner": "CSDS owner",
              "mitigation": "KPI-05 exclusion rules + CSDS-like cross-check", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-17", "residual_risk": "High", "linked_deliverable": "reporting-assurance-during-migration"},
             {"risk_id": "R012", "risk_description": "Local and national definitions diverge post-migration", "owner": "Mandatory reporting owner",
              "mitigation": "Document both in register; reconcile monthly", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-21", "residual_risk": "Medium", "linked_deliverable": "source-to-report-map"},
             {"risk_id": "R013", "risk_description": "Dashboard feed succeeds but measure meaning has changed", "owner": "Performance lead",
              "mitigation": "Confidence model + withhold from Board until signed off", "confidence_impact": "High", "status": "Open",
              "last_reviewed": "2026-03-20", "residual_risk": "High", "linked_deliverable": "reporting-assurance-during-migration"},
         ]),
        ("kpi_definitions_register.csv",
         ["kpi_id", "kpi_name", "definition", "agreed_definition_text", "service_definition", "system_capture",
          "fact_table_definition", "reporting_use", "exclusions_caveats", "validation_check", "owners_sign_off",
          "national_or_local", "owner", "source", "validation", "agreed_date", "sign_off_owner", "status",
          "migration_phase", "linked_kpi_option"],
         [
             {"kpi_id": "KPI-01", "kpi_name": "Referrals received", "definition": "Agreed hybrid OPT-C",
              "agreed_definition_text": "Pre-Feb-2026: ReferralDate on Legendary case. From Feb-2026: ACCESS_ACCEPTED excluding admin/duplicate and rejected unless CLINICAL_TRIAGE",
              "service_definition": "A request for the service to consider accepting a patient onto the MH access pathway.",
              "system_capture": "Old (Legendary Care): staff open a case and record referral received date. New (PathwayOne): access actions — referral sent, received, accepted or rejected.",
              "fact_table_definition": "Pre-migration: count Legendary case records with referral_received_datetime in month. Post-migration: count derived referral episodes where agreed access-action rule identifies a valid referral.",
              "reporting_use": "Local demand monitoring and MHSDS-like mandatory reporting — inclusion rules documented separately for each.",
              "exclusions_caveats": "Rejected referrals may still count as received depending on rejection reason (e.g. DRH-PAT-002896). Duplicates and admin actions excluded from demand but monitored in DQ.",
              "validation_check": "Compare monthly counts against old case extract during parallel running; sample rejected referrals with service leads; monitor unmapped rejection reasons.",
              "owners_sign_off": "Service lead (operational); BI (implementation); Performance (reporting use); directorate lead (final sign-off).",
              "national_or_local": "Both", "owner": "Performance lead",
              "source": "legendary_cmht_cases + pathwayone_actions", "validation": "Monthly reconciliation",
              "agreed_date": "2026-03-25", "sign_off_owner": "Directorate lead", "status": "Agreed pending workshop",
              "migration_phase": "D", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-02", "kpi_name": "Pathway start", "definition": "First CARE_FIRST_CONTACT after ACCESS_ACCEPTED",
              "agreed_definition_text": "First CARE_FIRST_CONTACT date where prior ACCESS_ACCEPTED exists within same pathway episode",
              "service_definition": "The point at which the patient begins active care on the pathway after acceptance.",
              "system_capture": "Old: PathwayStartDate on case (often same as referral). New: first CARE_FIRST_CONTACT action after ACCESS_ACCEPTED.",
              "fact_table_definition": "Derive pathway_start_date from first qualifying CARE_FIRST_CONTACT linked to accepted access episode.",
              "reporting_use": "Waiting time from referral to pathway start; local performance and waiting-list risk reports.",
              "exclusions_caveats": "Gap between access accepted and first contact affects waiting metrics — 12-day gaps flagged in vignettes.",
              "validation_check": "Compare old PathwayStartDate vs new first-contact rule for sample patients during parallel run.",
              "owners_sign_off": "CMHT clinical lead (operational); service manager; BI lead.",
              "national_or_local": "Local", "owner": "Service manager", "source": "pathwayone_actions",
              "validation": "Service validation", "agreed_date": "2026-03-20", "sign_off_owner": "CMHT clinical lead",
              "status": "Agreed", "migration_phase": "D", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-03", "kpi_name": "Waiting list stock", "definition": "Open ACCESS_WAITING at month end",
              "agreed_definition_text": "Count ACCESS_WAITING actions open on last day of month; exclude INVALID_TEAM",
              "service_definition": "Patients accepted onto the pathway but not yet had first contact — waiting for access.",
              "system_capture": "Old: case status Waiting on Legendary. New: ACCESS_WAITING action open at month end.",
              "fact_table_definition": "Count ACCESS_WAITING actions where action_end is null or after month-end; join dim_team excluding INVALID_TEAM.",
              "reporting_use": "Local waiting-list risk report and capacity planning meetings.",
              "exclusions_caveats": "INVALID_TEAM rows excluded; team remap failures can inflate or deflate stock.",
              "validation_check": "Compare old case Waiting stock vs new action stock by team for Mar 2026.",
              "owners_sign_off": "Service manager (operational); performance lead (reporting).",
              "national_or_local": "Local", "owner": "Service manager", "source": "pathwayone_actions",
              "validation": "Compared to old case Waiting", "agreed_date": "", "sign_off_owner": "Service manager",
              "status": "Draft", "migration_phase": "D", "linked_kpi_option": "OPT-B"},
             {"kpi_id": "KPI-04", "kpi_name": "First contact rate", "definition": "First contact within 14 days of referral",
              "agreed_definition_text": "Numerator: first CARE_FIRST_CONTACT within 14d of referral date. Denominator: agreed referrals (KPI-01)",
              "service_definition": "Proportion of referrals where the patient is seen within 14 days of referral received.",
              "system_capture": "Referral date from agreed KPI-01; first contact from CARE_FIRST_CONTACT action.",
              "fact_table_definition": "Numerator: count referrals with days_to_first_contact <= 14. Denominator: fact_referral_agreed (KPI-01).",
              "reporting_use": "Local and national access standards; senior performance brief headline.",
              "exclusions_caveats": "Denominator must use agreed referral definition — not dashboard count. Rejected-referral rule affects both.",
              "validation_check": "Test against known patients pre-embed; reconcile numerator/denominator monthly.",
              "owners_sign_off": "Clinical lead (standard); performance lead (reporting).",
              "national_or_local": "Both", "owner": "Clinical lead", "source": "Both systems",
              "validation": "Definition tested pre-embed", "agreed_date": "2026-02-15", "sign_off_owner": "Clinical lead",
              "status": "Agreed", "migration_phase": "C", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-05", "kpi_name": "Activity contacts", "definition": "CARE_ONGOING + CARE_FIRST_CONTACT",
              "agreed_definition_text": "Clinical care actions only; exclude ADMIN_CANCEL and duplicate ActionId",
              "service_definition": "Clinical contacts delivered to patients — assessments, interventions, ongoing care.",
              "system_capture": "Old: ContactCount on case. New: CARE_ONGOING and CARE_FIRST_CONTACT actions (admin actions separate).",
              "fact_table_definition": "Count care actions in month from fact_activity; exclude ADMIN_CANCEL, duplicate ActionId, non-clinical action types.",
              "reporting_use": "CSDS-like mandatory community activity return and local productivity pack.",
              "exclusions_caveats": "Admin actions can inflate counts if not excluded — vignette DRH-PAT-003201. National rules may differ from local.",
              "validation_check": "CSDS-like cross-check; weekly DQ on ActionId duplicates and admin flags.",
              "owners_sign_off": "CSDS owner (mandatory); service manager (local); BI lead (implementation).",
              "national_or_local": "National", "owner": "CSDS owner", "source": "pathwayone_actions",
              "validation": "CSDS-like cross-check", "agreed_date": "", "sign_off_owner": "CSDS owner",
              "status": "Pending reconciliation", "migration_phase": "D", "linked_kpi_option": "OPT-B"},
             {"kpi_id": "KPI-06", "kpi_name": "DNA rate", "definition": "DNA contacts / scheduled contacts",
              "agreed_definition_text": "DNA flag on care actions; denominator scheduled care actions in month",
              "service_definition": "Patients who did not attend a scheduled clinical contact.",
              "system_capture": "Old: DNA recorded on case contact. New: CARE_DNA action or DNA flag on scheduled CARE_* action.",
              "fact_table_definition": "Numerator: DNA-flagged care actions. Denominator: scheduled care actions in reporting month.",
              "reporting_use": "Local demand-capacity pack and service recovery meetings.",
              "exclusions_caveats": "Cancelled vs DNA must be distinguished; admin cancellations excluded from denominator.",
              "validation_check": "Weekly DQ check; compare DNA rate trend before and after migration.",
              "owners_sign_off": "Service manager (operational and reporting).",
              "national_or_local": "Local", "owner": "Service manager", "source": "pathwayone_actions",
              "validation": "Weekly DQ check", "agreed_date": "2026-04-01", "sign_off_owner": "Service manager",
              "status": "Agreed", "migration_phase": "F", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-07", "kpi_name": "Open caseload", "definition": "Open pathways at month end",
              "agreed_definition_text": "ACCESS_ACCEPTED without OUTCOME_CLOSED in month; hybrid case logic pre-Feb",
              "service_definition": "Patients actively on the pathway at month end — accepted and not yet closed.",
              "system_capture": "Old: open case count on Legendary. New: accepted access without outcome closure in period.",
              "fact_table_definition": "Hybrid: pre-Feb use case open logic; post-Feb derive from access/outcome action pairs.",
              "reporting_use": "Local caseload management and workforce planning.",
              "exclusions_caveats": "Definition of open differs from waiting stock — includes post-first-contact patients.",
              "validation_check": "Monthly stock reconcile against service manager caseload review.",
              "owners_sign_off": "Performance lead; service manager (operational validation).",
              "national_or_local": "Local", "owner": "Performance lead", "source": "Both systems",
              "validation": "Monthly stock reconcile", "agreed_date": "", "sign_off_owner": "Performance lead",
              "status": "Draft", "migration_phase": "D", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-08", "kpi_name": "Agency cost per contact", "definition": "Agency spend / contacts delivered",
              "agreed_definition_text": "LedgerWise agency postings / agreed activity contacts (KPI-05)",
              "service_definition": "Cost of agency staff per clinical contact delivered — workforce pressure indicator.",
              "system_capture": "Finance: agency postings in LedgerWise. Activity: agreed KPI-05 contacts from PathwayOne.",
              "fact_table_definition": "Sum agency ledger lines in month / count fact_activity contacts (KPI-05 rules).",
              "reporting_use": "Local demand-capacity pack and finance-directorate review.",
              "exclusions_caveats": "Activity definition must match KPI-05 — admin inflation affects cost-per-contact.",
              "validation_check": "Finance review of ledger mapping; cross-check activity denominator monthly.",
              "owners_sign_off": "Finance BP (cost); service manager (activity); finance directorate (sign-off).",
              "national_or_local": "Local", "owner": "Finance BP", "source": "LedgerWise + pathwayone_actions",
              "validation": "Finance review", "agreed_date": "2026-04-10", "sign_off_owner": "Finance directorate",
              "status": "Agreed", "migration_phase": "F", "linked_kpi_option": "n/a"},
             {"kpi_id": "KPI-09", "kpi_name": "Pathway closure", "definition": "OUTCOME_CLOSED in reporting month",
              "agreed_definition_text": "OUTCOME_CLOSED action in month with agreed outcome type mapping",
              "service_definition": "Patient pathway formally closed — discharged, transferred or otherwise ended.",
              "system_capture": "Old: ClosureDate and outcome on case. New: OUTCOME_CLOSED action with outcome type.",
              "fact_table_definition": "Count OUTCOME_CLOSED actions in reporting month; map outcome types to agreed categories.",
              "reporting_use": "Local throughput and caseload turnover; supports waiting-list interpretation.",
              "exclusions_caveats": "Admin closures vs clinical closures must be distinguished; transfer-out rules differ local vs national.",
              "validation_check": "Sample closed cases with service leads; compare old closure count vs new for parallel months.",
              "owners_sign_off": "Clinical lead (outcome meaning); service manager; BI lead.",
              "national_or_local": "Local", "owner": "Service manager", "source": "pathwayone_actions",
              "validation": "Service validation", "agreed_date": "", "sign_off_owner": "Clinical lead",
              "status": "Draft", "migration_phase": "D", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-10", "kpi_name": "Outcome", "definition": "Agreed outcome type at closure",
              "agreed_definition_text": "Map OUTCOME_* action types to agreed outcome categories (recovered, transferred, DNA discharge, etc.)",
              "service_definition": "What happened to the patient at end of pathway — recovery, transfer, decline, etc.",
              "system_capture": "Old: OutcomeText on case. New: outcome type on OUTCOME_CLOSED or OUTCOME_* actions.",
              "fact_table_definition": "Derive outcome_category from action outcome type via pathway_status_map crosswalk.",
              "reporting_use": "Local service quality review; may feed mandatory returns where outcome fields required.",
              "exclusions_caveats": "Free-text outcomes on old system do not map 1:1 to new coded types — manual review for edge cases.",
              "validation_check": "Review unmapped outcome codes monthly; sample with clinical lead.",
              "owners_sign_off": "Clinical lead (categories); mandatory reporting owner where national fields apply.",
              "national_or_local": "Both", "owner": "Clinical lead", "source": "pathwayone_actions + pathway_status_map",
              "validation": "Outcome mapping review", "agreed_date": "", "sign_off_owner": "Clinical lead",
              "status": "Draft", "migration_phase": "D", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-11", "kpi_name": "Reporting month allocation", "definition": "Which month an event counts in",
              "agreed_definition_text": "Facilitated rule per KPI: referral = received month; activity = action month; stock = month-end snapshot",
              "service_definition": "When a service event counts for monthly performance — not always obvious after migration.",
              "system_capture": "Old: ReportingMonth field on case. New: ActionDate per event — no single case field.",
              "fact_table_definition": "Per-KPI allocation rules in register; warehouse applies reporting_month dimension consistently.",
              "reporting_use": "All monthly KPIs and mandatory returns — underpins reconciliation.",
              "exclusions_caveats": "Events near month boundary can shift counts; parallel-run months need explicit rules.",
              "validation_check": "Reconcile month-boundary vignettes; compare old ReportingMonth vs new rules.",
              "owners_sign_off": "Performance lead (facilitation); BI lead (implementation); mandatory reporting owner.",
              "national_or_local": "Both", "owner": "Performance lead", "source": "Both systems",
              "validation": "Monthly reconciliation", "agreed_date": "2026-03-15", "sign_off_owner": "Performance lead",
              "status": "Agreed", "migration_phase": "D", "linked_kpi_option": "OPT-C"},
             {"kpi_id": "KPI-12", "kpi_name": "Team ownership", "definition": "Responsible team for pathway/event",
              "agreed_definition_text": "TeamCode on action mapped via team_service_code_map; exclude INVALID_TEAM",
              "service_definition": "Which CMHT or access team owns the patient for performance and capacity purposes.",
              "system_capture": "Old: ResponsibleTeam on case. New: TeamCode on each action — can change mid-pathway.",
              "fact_table_definition": "Join actions to dim_team via team_service_code_map; flag INVALID_TEAM for DQ not reporting.",
              "reporting_use": "All team-level local reports, waiting lists, productivity and demand packs.",
              "exclusions_caveats": "Team remap failures (DRH-PAT-000874) break team-level reporting; transfers change ownership mid-month.",
              "validation_check": "Crosswalk completeness check; compare old ResponsibleTeam vs new TeamCode for sample cases.",
              "owners_sign_off": "Service manager (operational teams); BI lead (crosswalk); performance lead (reporting).",
              "national_or_local": "Local", "owner": "Service manager", "source": "team_service_code_map + pathwayone_actions",
              "validation": "Team crosswalk validation", "agreed_date": "2026-03-10", "sign_off_owner": "Service manager",
              "status": "Agreed", "migration_phase": "D", "linked_kpi_option": "n/a"},
         ]),
        ("reporting_confidence_register.csv",
         ["report_name", "confidence_level", "as_at_month", "fallback_route", "usage_note", "publish_decision"],
         [
             {"report_name": "Executive MH dashboard", "confidence_level": "Low", "as_at_month": "2026-03",
              "fallback_route": "Manual reconciliation pack", "usage_note": "Do not use for Board without sign-off",
              "publish_decision": "Withhold from Board"},
             {"report_name": "MHSDS-like monthly", "confidence_level": "Medium", "as_at_month": "2026-03",
              "fallback_route": "Legacy pipeline fallback", "usage_note": "Owner confirmation required",
              "publish_decision": "Submit 134 not 154"},
             {"report_name": "Local demand-capacity pack", "confidence_level": "High", "as_at_month": "2026-04",
              "fallback_route": "n/a", "usage_note": "Suitable for service review",
              "publish_decision": "Safe for service review"},
             {"report_name": "Waiting list risk report", "confidence_level": "Medium", "as_at_month": "2026-03",
              "fallback_route": "Old case stock comparison", "usage_note": "Flag definition change",
              "publish_decision": "Use with definition caveat"},
         ]),
        ("demand_capacity_weekly.csv",
         ["week", "demand", "capacity", "backlog", "workforce_availability_index", "agency_spend_gbp",
          "contacts_delivered", "dna_rate", "referrals_in_week", "median_wait_days", "long_wait_count",
          "opt_c_referrals", "dashboard_referrals"],
         [
             {"week": "2026-W06", "demand": "172", "capacity": "178", "backlog": "108", "workforce_availability_index": "0.94",
              "agency_spend_gbp": "13200", "contacts_delivered": "165", "dna_rate": "0.07", "referrals_in_week": "35",
              "median_wait_days": "10", "long_wait_count": "8", "opt_c_referrals": "33", "dashboard_referrals": "36"},
             {"week": "2026-W07", "demand": "175", "capacity": "179", "backlog": "112", "workforce_availability_index": "0.93",
              "agency_spend_gbp": "13350", "contacts_delivered": "167", "dna_rate": "0.07", "referrals_in_week": "36",
              "median_wait_days": "10", "long_wait_count": "9", "opt_c_referrals": "34", "dashboard_referrals": "37"},
             {"week": "2026-W08", "demand": "178", "capacity": "179", "backlog": "116", "workforce_availability_index": "0.93",
              "agency_spend_gbp": "13500", "contacts_delivered": "168", "dna_rate": "0.08", "referrals_in_week": "36",
              "median_wait_days": "11", "long_wait_count": "10", "opt_c_referrals": "34", "dashboard_referrals": "37"},
             {"week": "2026-W09", "demand": "182", "capacity": "180", "backlog": "121", "workforce_availability_index": "0.92",
              "agency_spend_gbp": "13680", "contacts_delivered": "170", "dna_rate": "0.08", "referrals_in_week": "37",
              "median_wait_days": "11", "long_wait_count": "11", "opt_c_referrals": "35", "dashboard_referrals": "38"},
             {"week": "2026-W10", "demand": "185", "capacity": "180", "backlog": "125", "workforce_availability_index": "0.92",
              "agency_spend_gbp": "13875", "contacts_delivered": "172", "dna_rate": "0.08", "referrals_in_week": "38",
              "median_wait_days": "11", "long_wait_count": "12", "opt_c_referrals": "36", "dashboard_referrals": "39"},
             {"week": "2026-W11", "demand": "188", "capacity": "182", "backlog": "131", "workforce_availability_index": "0.91",
              "agency_spend_gbp": "13980", "contacts_delivered": "174", "dna_rate": "0.08", "referrals_in_week": "39",
              "median_wait_days": "11", "long_wait_count": "14", "opt_c_referrals": "37", "dashboard_referrals": "40"},
             {"week": "2026-W12", "demand": "192", "capacity": "184", "backlog": "138", "workforce_availability_index": "0.90",
              "agency_spend_gbp": "14100", "contacts_delivered": "176", "dna_rate": "0.09", "referrals_in_week": "40",
              "median_wait_days": "12", "long_wait_count": "16", "opt_c_referrals": "38", "dashboard_referrals": "41"},
             {"week": "2026-W13", "demand": "196", "capacity": "186", "backlog": "146", "workforce_availability_index": "0.89",
              "agency_spend_gbp": "14220", "contacts_delivered": "178", "dna_rate": "0.09", "referrals_in_week": "41",
              "median_wait_days": "12", "long_wait_count": "18", "opt_c_referrals": "39", "dashboard_referrals": "42"},
             {"week": "2026-W14", "demand": "200", "capacity": "188", "backlog": "158", "workforce_availability_index": "0.88",
              "agency_spend_gbp": "14370", "contacts_delivered": "180", "dna_rate": "0.09", "referrals_in_week": "42",
              "median_wait_days": "12", "long_wait_count": "22", "opt_c_referrals": "40", "dashboard_referrals": "43"},
             {"week": "2026-W15", "demand": "202", "capacity": "190", "backlog": "168", "workforce_availability_index": "0.87",
              "agency_spend_gbp": "14580", "contacts_delivered": "182", "dna_rate": "0.09", "referrals_in_week": "43",
              "median_wait_days": "12", "long_wait_count": "24", "opt_c_referrals": "41", "dashboard_referrals": "44"},
             {"week": "2026-W16", "demand": "204", "capacity": "192", "backlog": "178", "workforce_availability_index": "0.86",
              "agency_spend_gbp": "14760", "contacts_delivered": "184", "dna_rate": "0.10", "referrals_in_week": "43",
              "median_wait_days": "12", "long_wait_count": "26", "opt_c_referrals": "42", "dashboard_referrals": "45"},
             {"week": "2026-W17", "demand": "206", "capacity": "194", "backlog": "192", "workforce_availability_index": "0.86",
              "agency_spend_gbp": "14940", "contacts_delivered": "186", "dna_rate": "0.10", "referrals_in_week": "44",
              "median_wait_days": "12", "long_wait_count": "28", "opt_c_referrals": "43", "dashboard_referrals": "46"},
             {"week": "2026-W18", "demand": "208", "capacity": "195", "backlog": "212", "workforce_availability_index": "0.85",
              "agency_spend_gbp": "15180", "contacts_delivered": "188", "dna_rate": "0.10", "referrals_in_week": "45",
              "median_wait_days": "12", "long_wait_count": "32", "opt_c_referrals": "44", "dashboard_referrals": "47"},
             {"week": "2026-W19", "demand": "212", "capacity": "197", "backlog": "228", "workforce_availability_index": "0.84",
              "agency_spend_gbp": "15420", "contacts_delivered": "190", "dna_rate": "0.10", "referrals_in_week": "46",
              "median_wait_days": "12", "long_wait_count": "36", "opt_c_referrals": "45", "dashboard_referrals": "48"},
             {"week": "2026-W20", "demand": "215", "capacity": "198", "backlog": "246", "workforce_availability_index": "0.83",
              "agency_spend_gbp": "15690", "contacts_delivered": "192", "dna_rate": "0.11", "referrals_in_week": "47",
              "median_wait_days": "12", "long_wait_count": "40", "opt_c_referrals": "46", "dashboard_referrals": "49"},
             {"week": "2026-W21", "demand": "218", "capacity": "200", "backlog": "264", "workforce_availability_index": "0.82",
              "agency_spend_gbp": "15960", "contacts_delivered": "195", "dna_rate": "0.11", "referrals_in_week": "48",
              "median_wait_days": "12", "long_wait_count": "44", "opt_c_referrals": "48", "dashboard_referrals": "52"},
         ]),
        ("mandatory_mhsds_like_monthly.csv",
         ["provider_ods", "reporting_month", "measure", "value", "notes"],
         [
             {"provider_ods": TRUST_ODS, "reporting_month": "2026-03", "measure": "Referrals", "value": "154", "notes": "Dashboard logic — not agreed"},
             {"provider_ods": TRUST_ODS, "reporting_month": "2026-03", "measure": "Referrals", "value": "134", "notes": "Agreed definition"},
             {"provider_ods": TRUST_ODS, "reporting_month": "2026-03", "measure": "Contacts", "value": "420", "notes": "CSDS-like cross-check"},
         ]),
        ("mandatory_csds_like_monthly.csv",
         ["provider_ods", "reporting_month", "activity_type", "count", "notes"],
         [
             {"provider_ods": TRUST_ODS, "reporting_month": "2026-03", "activity_type": "Assessment", "count": "890", "notes": "Illustrative"},
             {"provider_ods": TRUST_ODS, "reporting_month": "2026-03", "activity_type": "Clinical Intervention", "count": "1120", "notes": "Illustrative"},
         ]),
        ("mandatory_adc_like_monthly.csv",
         ["provider_ods", "reporting_month", "measure_code", "value", "notes"],
         [
             {"provider_ods": TRUST_ODS, "reporting_month": "2026-03", "measure_code": "ADC_E07_ANALOGUE", "value": "2840", "notes": "Urgent care contacts — illustrative"},
         ]),
        ("vignette_index.csv",
         ["PatientPseudoId", "scenario_type", "migration_phase", "centrepiece_display", "notes", "old_vs_new_summary"],
         [
             {"PatientPseudoId": ANCHOR_PATIENT, "scenario_type": "anchor_patient", "migration_phase": "D", "centrepiece_display": "True",
              "notes": "Rejected referral — old counts received", "old_vs_new_summary": "Old=1 referral; new default=0"},
             {"PatientPseudoId": "DRH-PAT-001104", "scenario_type": "parallel_duplicate", "migration_phase": "B", "centrepiece_display": "False",
              "notes": "Both systems during parallel run", "old_vs_new_summary": "Duplicate risk"},
             {"PatientPseudoId": "DRH-PAT-001552", "scenario_type": "pathway_start_ambiguity", "migration_phase": "D", "centrepiece_display": "False",
              "notes": "12-day gap access vs first contact", "old_vs_new_summary": "Pathway start differs"},
             {"PatientPseudoId": "DRH-PAT-003201", "scenario_type": "admin_inflation", "migration_phase": "D", "centrepiece_display": "False",
              "notes": "Admin actions inflate activity", "old_vs_new_summary": "Activity count diverges"},
             {"PatientPseudoId": "DRH-PAT-000874", "scenario_type": "missing_team_code", "migration_phase": "D", "centrepiece_display": "False",
              "notes": "INVALID_TEAM in new system", "old_vs_new_summary": "Team remap failed"},
         ]),
        ("reporting_requirements_map.csv",
         ["req_id", "stakeholder", "business_question", "mandatory_or_local", "kpi_ref", "report_ref", "priority"],
         [
             {"req_id": "REQ-01", "stakeholder": "NHSE mandatory returns", "business_question": "How many MH referrals received?",
              "mandatory_or_local": "Mandatory", "kpi_ref": "KPI-01", "report_ref": "MHSDS-like monthly", "priority": "Must-not-fail"},
             {"req_id": "REQ-02", "stakeholder": "Directorate lead", "business_question": "Are we meeting first contact standards?",
              "mandatory_or_local": "Local", "kpi_ref": "KPI-04", "report_ref": "Senior performance brief", "priority": "High"},
             {"req_id": "REQ-03", "stakeholder": "CMHT service manager", "business_question": "What is waiting list pressure by team?",
              "mandatory_or_local": "Local", "kpi_ref": "KPI-03", "report_ref": "Waiting list risk", "priority": "High"},
             {"req_id": "REQ-04", "stakeholder": "Board", "business_question": "Headline MH access performance trend?",
              "mandatory_or_local": "Local", "kpi_ref": "KPI-01", "report_ref": "Executive MH dashboard", "priority": "Must-not-fail"},
             {"req_id": "REQ-05", "stakeholder": "CSDS return owner", "business_question": "Community activity counts?",
              "mandatory_or_local": "Mandatory", "kpi_ref": "KPI-05", "report_ref": "CSDS-like monthly", "priority": "Must-not-fail"},
             {"req_id": "REQ-06", "stakeholder": "Finance", "business_question": "Agency cost vs activity delivered?",
              "mandatory_or_local": "Local", "kpi_ref": "KPI-08", "report_ref": "Demand-capacity pack", "priority": "Medium"},
             {"req_id": "REQ-07", "stakeholder": "IM&T programme", "business_question": "Are feeds aligned post-cutover?",
              "mandatory_or_local": "Local", "kpi_ref": "n/a", "report_ref": "Validation pack", "priority": "High"},
         ]),
        ("report_catalogue.csv",
         ["report_id", "report_name", "audience", "frequency", "owner", "requirement_ids", "confidence_mar2026", "data_sources"],
         [
             {"report_id": "RPT-01", "report_name": "Executive MH dashboard", "audience": "SLT", "frequency": "Monthly",
              "owner": "Performance lead", "requirement_ids": "REQ-04", "confidence_mar2026": "Low", "data_sources": "Blended legacy pipeline"},
             {"report_id": "RPT-02", "report_name": "MHSDS-like monthly", "audience": "NHSE", "frequency": "Monthly",
              "owner": "Mandatory reporting owner", "requirement_ids": "REQ-01", "confidence_mar2026": "Medium", "data_sources": "fact_referral + fact_access"},
             {"report_id": "RPT-03", "report_name": "CSDS-like monthly", "audience": "NHSE", "frequency": "Monthly",
              "owner": "CSDS owner", "requirement_ids": "REQ-05", "confidence_mar2026": "Medium", "data_sources": "fact_activity"},
             {"report_id": "RPT-04", "report_name": "Waiting list and pathway risk", "audience": "CMHT managers", "frequency": "Weekly",
              "owner": "Service manager", "requirement_ids": "REQ-03", "confidence_mar2026": "Medium", "data_sources": "pathwayone_actions"},
             {"report_id": "RPT-05", "report_name": "Demand and capacity pack", "audience": "Directorate", "frequency": "Weekly",
              "owner": "Performance lead", "requirement_ids": "REQ-06", "confidence_mar2026": "High", "data_sources": "demand_capacity_weekly"},
             {"report_id": "RPT-06", "report_name": "Senior performance brief", "audience": "SLT / Board", "frequency": "Monthly",
              "owner": "Performance lead", "requirement_ids": "REQ-02 REQ-04", "confidence_mar2026": "Low", "data_sources": "Multiple — see source map"},
             {"report_id": "RPT-07", "report_name": "Data quality and confidence", "audience": "BI + performance", "frequency": "Monthly",
              "owner": "BI lead", "requirement_ids": "REQ-07", "confidence_mar2026": "High", "data_sources": "validation_checks_register"},
             {"report_id": "RPT-08", "report_name": "Reconciliation pack", "audience": "Performance + BI", "frequency": "Monthly",
              "owner": "Performance lead", "requirement_ids": "REQ-01 REQ-04", "confidence_mar2026": "High", "data_sources": "reconciliation_monthly"},
         ]),
        ("validation_checks_register.csv",
         ["check_id", "rule_description", "source", "expected", "mar2026_result", "pass_fail", "action"],
         [
             {"check_id": "VAL-01", "rule_description": "No duplicate ActionId in month", "source": "pathwayone_actions",
              "expected": "0 duplicates", "mar2026_result": "1 duplicate (DRH-PAT-005663)", "pass_fail": "Fail", "action": "Exclude in OPT-C"},
             {"check_id": "VAL-02", "rule_description": "All teams map via crosswalk", "source": "team_service_code_map",
              "expected": "0 INVALID_TEAM", "mar2026_result": "1 INVALID_TEAM row", "pass_fail": "Fail", "action": "Escalate to service manager"},
             {"check_id": "VAL-03", "rule_description": "Referral count within ±15% of agreed", "source": "reconciliation_monthly",
              "expected": "Dashboard within 15% of agreed", "mar2026_result": "+14.9% (154 vs 134)", "pass_fail": "Fail", "action": "Do not publish dashboard figure"},
             {"check_id": "VAL-04", "rule_description": "Orphan cases without actions post-cutover", "source": "legendary_cmht_cases",
              "expected": "<5% orphan", "mar2026_result": "3.2%", "pass_fail": "Pass", "action": "Monitor"},
             {"check_id": "VAL-05", "rule_description": "Admin actions excluded from activity", "source": "pathwayone_actions",
              "expected": "ADMIN_CANCEL excluded", "mar2026_result": "2 admin rows flagged", "pass_fail": "Pass", "action": "Embedded in KPI-05"},
             {"check_id": "VAL-06", "rule_description": "MHSDS-like matches agreed referrals", "source": "mandatory_mhsds_like_monthly",
              "expected": "Agreed value submitted", "mar2026_result": "154 submitted (dashboard)", "pass_fail": "Fail", "action": "Resubmit with 134 after sign-off"},
         ]),
        ("reconciliation_detail_mar2026.csv",
         ["team_code", "old_case_referrals", "new_action_referrals", "agreed_referrals", "dashboard_referrals", "notes"],
         [
             {"team_code": "AA-MH-NORTH-01", "old_case_referrals": "42", "new_action_referrals": "48", "agreed_referrals": "38", "dashboard_referrals": "44", "notes": "Admin inflation + duplicates"},
             {"team_code": "AA-MH-SOUTH-01", "old_case_referrals": "38", "new_action_referrals": "45", "agreed_referrals": "36", "dashboard_referrals": "41", "notes": "Parallel duplicate period"},
             {"team_code": "AA-MH-EAST-01", "old_case_referrals": "35", "new_action_referrals": "40", "agreed_referrals": "33", "dashboard_referrals": "37", "notes": "Pathway start ambiguity"},
             {"team_code": "AA-CRISIS-01", "old_case_referrals": "22", "new_action_referrals": "25", "agreed_referrals": "20", "dashboard_referrals": "23", "notes": "Rejected referral definition"},
             {"team_code": "AA-PCL-01", "old_case_referrals": "14", "new_action_referrals": "10", "agreed_referrals": "7", "dashboard_referrals": "9", "notes": "National yes local no"},
             {"team_code": "TOTAL", "old_case_referrals": "151", "new_action_referrals": "168", "agreed_referrals": "134", "dashboard_referrals": "154", "notes": "Trust total Mar 2026"},
         ]),
        ("productivity_by_team.csv",
         ["team_code", "week", "available_hours", "contacts_delivered", "contacts_per_wte", "wte_available",
          "agency_spend_gbp", "dna_count", "cost_per_contact"],
         [
             {"team_code": "AA-MH-NORTH-01", "week": "2026-W10", "available_hours": "640", "contacts_delivered": "90", "contacts_per_wte": "43", "wte_available": "15.0", "agency_spend_gbp": "3200", "dna_count": "7", "cost_per_contact": "35.56"},
             {"team_code": "AA-MH-NORTH-01", "week": "2026-W14", "available_hours": "620", "contacts_delivered": "88", "contacts_per_wte": "42", "wte_available": "14.8", "agency_spend_gbp": "3300", "dna_count": "8", "cost_per_contact": "37.50"},
             {"team_code": "AA-MH-NORTH-01", "week": "2026-W18", "available_hours": "600", "contacts_delivered": "85", "contacts_per_wte": "40", "wte_available": "14.5", "agency_spend_gbp": "3400", "dna_count": "9", "cost_per_contact": "40.00"},
             {"team_code": "AA-MH-NORTH-01", "week": "2026-W21", "available_hours": "580", "contacts_delivered": "82", "contacts_per_wte": "39", "wte_available": "14.2", "agency_spend_gbp": "3500", "dna_count": "10", "cost_per_contact": "42.68"},
             {"team_code": "AA-MH-SOUTH-01", "week": "2026-W10", "available_hours": "560", "contacts_delivered": "78", "contacts_per_wte": "42", "wte_available": "14.0", "agency_spend_gbp": "3800", "dna_count": "8", "cost_per_contact": "48.72"},
             {"team_code": "AA-MH-SOUTH-01", "week": "2026-W14", "available_hours": "540", "contacts_delivered": "76", "contacts_per_wte": "41", "wte_available": "13.5", "agency_spend_gbp": "4000", "dna_count": "9", "cost_per_contact": "52.63"},
             {"team_code": "AA-MH-SOUTH-01", "week": "2026-W18", "available_hours": "525", "contacts_delivered": "74", "contacts_per_wte": "39", "wte_available": "13.2", "agency_spend_gbp": "4200", "dna_count": "10", "cost_per_contact": "56.76"},
             {"team_code": "AA-MH-SOUTH-01", "week": "2026-W21", "available_hours": "510", "contacts_delivered": "71", "contacts_per_wte": "38", "wte_available": "12.9", "agency_spend_gbp": "4400", "dna_count": "11", "cost_per_contact": "61.97"},
             {"team_code": "AA-MH-EAST-01", "week": "2026-W10", "available_hours": "520", "contacts_delivered": "72", "contacts_per_wte": "39", "wte_available": "13.0", "agency_spend_gbp": "2900", "dna_count": "6", "cost_per_contact": "40.28"},
             {"team_code": "AA-MH-EAST-01", "week": "2026-W14", "available_hours": "510", "contacts_delivered": "70", "contacts_per_wte": "38", "wte_available": "12.8", "agency_spend_gbp": "3000", "dna_count": "7", "cost_per_contact": "42.86"},
             {"team_code": "AA-MH-EAST-01", "week": "2026-W18", "available_hours": "500", "contacts_delivered": "69", "contacts_per_wte": "37", "wte_available": "12.6", "agency_spend_gbp": "3100", "dna_count": "8", "cost_per_contact": "44.93"},
             {"team_code": "AA-MH-EAST-01", "week": "2026-W21", "available_hours": "495", "contacts_delivered": "68", "contacts_per_wte": "37", "wte_available": "12.5", "agency_spend_gbp": "3200", "dna_count": "8", "cost_per_contact": "47.06"},
             {"team_code": "AA-CRISIS-01", "week": "2026-W10", "available_hours": "480", "contacts_delivered": "95", "contacts_per_wte": "52", "wte_available": "11.5", "agency_spend_gbp": "2100", "dna_count": "5", "cost_per_contact": "22.11"},
             {"team_code": "AA-CRISIS-01", "week": "2026-W14", "available_hours": "475", "contacts_delivered": "94", "contacts_per_wte": "51", "wte_available": "11.4", "agency_spend_gbp": "2150", "dna_count": "5", "cost_per_contact": "22.87"},
             {"team_code": "AA-CRISIS-01", "week": "2026-W18", "available_hours": "470", "contacts_delivered": "92", "contacts_per_wte": "50", "wte_available": "11.2", "agency_spend_gbp": "2200", "dna_count": "6", "cost_per_contact": "23.91"},
             {"team_code": "AA-CRISIS-01", "week": "2026-W21", "available_hours": "465", "contacts_delivered": "90", "contacts_per_wte": "49", "wte_available": "11.0", "agency_spend_gbp": "2250", "dna_count": "6", "cost_per_contact": "25.00"},
             {"team_code": "AA-PCL-01", "week": "2026-W14", "available_hours": "400", "contacts_delivered": "58", "contacts_per_wte": "44", "wte_available": "9.5", "agency_spend_gbp": "1800", "dna_count": "4", "cost_per_contact": "31.03"},
             {"team_code": "AA-PCL-01", "week": "2026-W18", "available_hours": "395", "contacts_delivered": "56", "contacts_per_wte": "43", "wte_available": "9.4", "agency_spend_gbp": "1850", "dna_count": "4", "cost_per_contact": "33.04"},
             {"team_code": "AA-PCL-01", "week": "2026-W21", "available_hours": "390", "contacts_delivered": "54", "contacts_per_wte": "42", "wte_available": "9.2", "agency_spend_gbp": "1900", "dna_count": "5", "cost_per_contact": "35.19"},
         ]),
        ("demand_capacity_insights.csv",
         ["insight_id", "headline", "evidence", "suggested_action", "status", "owner", "week"],
         [
             {"insight_id": "INS-01", "headline": "South team agency spend up 15% but contacts/WTE flat",
              "evidence": "AA-MH-SOUTH-01 WFA 0.82 vs North 0.92; agency £4,400 vs £3,500; contacts/WTE 38 vs 39",
              "suggested_action": "Roster review before further agency hire — discuss with South CMHT lead",
              "status": "Promoted", "owner": "Service manager", "week": "2026-W21"},
             {"insight_id": "INS-02", "headline": "DNA rate rising with median wait — recovery slots pilot",
              "evidence": "DNA 8%→11% W10–W21; median wait stable at 12d but long-wait count +32",
              "suggested_action": "Pilot DNA recovery slots in South team; review after 4 weeks",
              "status": "Under test", "owner": "Clinical lead", "week": "2026-W21"},
             {"insight_id": "INS-03", "headline": "Naive 4-week backlog forecast unreliable during definition change",
              "evidence": "Forecast overshot by 18% when dashboard referrals used instead of OPT-C",
              "suggested_action": "Dismiss forecast for Board; revisit post OPT-C sign-off (M5)",
              "status": "Dismissed", "owner": "Performance lead", "week": "2026-W18"},
             {"insight_id": "INS-04", "headline": "INVALID_TEAM rows inflate East waiting stock",
              "evidence": "VAL-02 fail; 1 INVALID_TEAM row maps to AA-MH-EAST-01 waiting count",
              "suggested_action": "Fix crosswalk before capacity meeting — do not allocate agency on bad stock",
              "status": "Promoted", "owner": "BI lead", "week": "2026-W21"},
             {"insight_id": "INS-05", "headline": "Caseload mix shift needs agreed KPI-07 before action",
              "evidence": "Open vs waiting ratio changed post-migration; KPI-07 still Draft",
              "suggested_action": "Park workforce modelling until caseload definition signed off",
              "status": "Parked", "owner": "Performance lead", "week": "2026-W21"},
         ]),
        ("ideas_under_test_register.csv",
         ["idea_id", "idea_name", "hypothesis", "test_method", "outcome", "status", "month",
          "linked_artefact", "problem", "small_test", "evidence", "decision", "next_step", "scale_safe_when"],
         [
             {"idea_id": "IDEA-01", "idea_name": "Weekly demand/capacity pack",
              "hypothesis": "One weekly view beats several spreadsheets",
              "test_method": "Prototype with 2 CMHT leads, 6 weeks",
              "outcome": "Promoted to deliverable #4",
              "status": "Promoted", "month": "M4", "linked_artefact": "demand-capacity-productivity",
              "problem": "CMHT managers run separate spreadsheets for referrals, waits, caseload and agency — often on different definitions during the Legendary Care to PathwayOne move.",
              "small_test": "Build a single weekly pack and run it with two CMHT leads for six weeks. Compare their capacity meetings against the old spreadsheet routine.",
              "evidence": "Managers use the pack in meetings without BI translation; agency and roster conversations reference the same figures; South/North variance prompts action (INS-01).",
              "decision": "Weekly capacity, agency spend and workforce allocation.",
              "next_step": "Promoted — owned by performance lead with CMHT sign-off; not scaled Trust-wide until a third team confirms value.",
              "scale_safe_when": "Managers change decisions because of the pack; OPT-C referral definition signed off; pack refreshed from agreed sources only."},
             {"idea_id": "IDEA-02", "idea_name": "Reporting assurance single pack",
              "hypothesis": "Risk, validation and confidence belong in one story",
              "test_method": "Merge three registers; review with BI + performance",
              "outcome": "Promoted — clearer publish gate",
              "status": "Promoted", "month": "M3", "linked_artefact": "reporting-assurance-during-migration",
              "problem": "Migration risk, validation checks and confidence ratings duplicated each other — sponsors read one page and missed the publish decision.",
              "small_test": "Draft one combined assurance page; walk BI lead and performance lead through March 2026 withhold scenario before replacing three separate deliverables.",
              "evidence": "Single narrative covers risks → checks → publish; March withhold of executive dashboard understood in one read-through.",
              "decision": "Whether figures are safe to publish to SLT, Board or mandatory returns.",
              "next_step": "Promoted as deliverable #3; monthly refresh owned by performance + BI.",
              "scale_safe_when": "Publish rules agreed with directorate; checks automated where possible; owners named for each must-not-fail report."},
             {"idea_id": "IDEA-03", "idea_name": "4-week backlog forecasting",
              "hypothesis": "Linear forecast helps agency planning",
              "test_method": "Forecast W18–W21 using dashboard referrals",
              "outcome": "Dismissed — 18% overshoot",
              "status": "Dismissed", "month": "M4", "linked_artefact": "demand_capacity_insights.csv",
              "problem": "Directorate asked for a simple backlog forecast to justify agency spend while waits were rising.",
              "small_test": "Four-week linear forecast using dashboard referral counts (W18–W21) compared to agreed OPT-C trend.",
              "evidence": "Forecast overshot actual backlog growth by 18% because dashboard referrals inflated demand during definition change (INS-03).",
              "decision": "Agency hire and short-term capacity spend.",
              "next_step": "Dismissed for Board use until OPT-C signed off and six weeks of stable agreed data exist.",
              "scale_safe_when": "n/a — misleading during migration; revisit post OPT-C sign-off (M5)."},
             {"idea_id": "IDEA-04", "idea_name": "SPC on referral counts",
              "hypothesis": "Control charts detect definition drift early",
              "test_method": "Pilot chart on Mar weekly referrals",
              "outcome": "Parked — too noisy in phase D",
              "status": "Parked", "month": "M4", "linked_artefact": "kpi-definitions-register",
              "problem": "Teams want an early warning when referral logic drifts — before mandatory returns or Board packs go wrong.",
              "small_test": "Plot weekly referrals on a control chart for March, using both dashboard and OPT-C series side by side.",
              "evidence": "Chart flagged false signals every time definition options changed; signal-to-noise unusable during parallel run.",
              "decision": "When to escalate suspected definition drift.",
              "next_step": "Park until OPT-C is signed off and at least three months of single-definition data exist.",
              "scale_safe_when": "One agreed numerator; stable feed; service managers understand limits of statistical rules."},
             {"idea_id": "IDEA-05", "idea_name": "Manager 1:1 performance conversation guide",
              "hypothesis": "Structured 1:1s improve underperforming teams",
              "test_method": "Pilot with 2 CMHT leads; template + prompts",
              "outcome": "South team pilot in progress",
              "status": "Under test", "month": "M4", "linked_artefact": "ideas-under-test",
              "problem": "Productivity variance by team (contacts per WTE) was visible in data but conversations with line managers were ad hoc and defensive.",
              "small_test": "Short conversation guide linked to weekly pack metrics; two CMHT leads trial for four weeks with South team focus.",
              "evidence": "Managers report clearer actions from 1:1s; at least one workforce action logged (roster review or training) per pilot team.",
              "decision": "Team performance support, training needs and whether underperformance needs formal HR pathway.",
              "next_step": "Continue pilot; pair with IDEA-08 if HR pathway test succeeds.",
              "scale_safe_when": "HR BP agrees template; trade unions consulted if needed; guide used without blaming individuals for definition artefacts."},
             {"idea_id": "IDEA-06", "idea_name": "DNA recovery slot analysis",
              "hypothesis": "Targeted recovery slots reduce DNA without extra WTE",
              "test_method": "Link DNA trend to wait; pilot in South",
              "outcome": "4-week South pilot agreed (INS-02)",
              "status": "Under test", "month": "M4", "linked_artefact": "demand_capacity_insights.csv",
              "problem": "DNA rate rose from 8% to 11% while median wait held at 12 days — patients disengaging before contact.",
              "small_test": "South team offers targeted recovery slots for long-wait DNA cases; track DNA and contacts for four weeks vs North baseline.",
              "evidence": "DNA rate and long-wait count move in the right direction without extra WTE; clinical lead signs off safety.",
              "decision": "Whether to expand recovery slot model to other CMHTs.",
              "next_step": "Review pilot at week four; link results to demand pack INS-02.",
              "scale_safe_when": "Pilot shows sustained DNA improvement; clinical governance agreed; capacity impact on other waits understood."},
             {"idea_id": "IDEA-07", "idea_name": "RosterFlow capacity integration",
              "hypothesis": "Roster hours improve workforce availability index",
              "test_method": "Join RosterFlow hours to weekly pack",
              "outcome": "Parked — PathwayOne unstable",
              "status": "Parked", "month": "M5", "linked_artefact": "demand-capacity-productivity",
              "problem": "Workforce availability index uses estimated hours; roster system may be more accurate once feeds stabilise.",
              "small_test": "Match RosterFlow available hours to WFA calculation for one team for four weeks.",
              "evidence": "Feed incomplete post-cutover; one team crosswalk still failing (INVALID_TEAM).",
              "decision": "Agency spend and roster planning in weekly pack.",
              "next_step": "Park until PathwayOne roster extract reliable and team crosswalk complete.",
              "scale_safe_when": "Roster feed validated against manual rota sample; WFA moves only when managers trust the hours."},
             {"idea_id": "IDEA-08", "idea_name": "PIP / underperformance support pathway",
              "hypothesis": "Productivity outliers need structured HR route",
              "test_method": "Pair outliers with conversation guide + HR BP",
              "outcome": "HR BP pilot; not scaled",
              "status": "Under test", "month": "M4", "linked_artefact": "ideas-under-test",
              "problem": "Contacts-per-WTE outliers were discussed in capacity meetings but without a fair, consistent HR-aligned route when performance concern was genuine.",
              "small_test": "Identify one team with sustained outlier metrics; HR BP and CMHT lead use conversation guide before any formal process.",
              "evidence": "Documented support plan or confirmed data/definition explanation; no pathway misuse for migration noise.",
              "decision": "Whether formal performance support is appropriate vs definition or caseload mix issue.",
              "next_step": "Complete HR BP pilot; do not scale until definition stable and IDEA-05 guide evaluated.",
              "scale_safe_when": "HR and clinical leads agree thresholds; metrics agreed in KPI register; pathway distinct from spreadsheet blame."},
             {"idea_id": "IDEA-09", "idea_name": "Trust-wide MH demand forecast",
              "hypothesis": "Statistical forecast supports directorate planning",
              "test_method": "Review time-series after clean data window",
              "outcome": "Parked — definition noise",
              "status": "Parked", "month": "M5", "linked_artefact": "six-months-trusted-performance",
              "problem": "Directorate wanted a twelve-month MH demand forecast for workforce and estate planning.",
              "small_test": "Review whether six months post-migration OPT-C data would support a simple time-series model.",
              "evidence": "Definition change and dashboard artefact invalidate historical series; IDEA-03 forecast failure confirms risk.",
              "decision": "Long-term workforce and estate investment.",
              "next_step": "Park; revisit in month twelve of stable agreed data if secondment extended or role permanent.",
              "scale_safe_when": "Six months single-definition referrals; forecast validated on hold-out period; clinical leads sign off assumptions."},
             {"idea_id": "IDEA-10", "idea_name": "Board slide confidence column",
              "hypothesis": "Leaders need explicit confidence per headline",
              "test_method": "Add column to senior brief; Mar 2026 draft",
              "outcome": "Embedded in senior brief template",
              "status": "Promoted", "month": "M5", "linked_artefact": "senior-performance-brief",
              "problem": "Board packs treated all KPIs as equally trustworthy — dangerous when dashboard still refreshes on old logic.",
              "small_test": "Add confidence column to senior brief template; draft March pack with executive dashboard marked Low and withheld from Board slide.",
              "evidence": "Directorate leads used confidence column in rehearsal; no accidental use of withheld dashboard figure.",
              "decision": "What is safe to present at Board and what needs a caveat conversation.",
              "next_step": "Promoted in senior brief template; confidence rules tied to assurance pack.",
              "scale_safe_when": "Confidence ladder adopted monthly; owners confirm ratings before circulation."},
             {"idea_id": "IDEA-11", "idea_name": "Real pressure vs data artefact review",
              "hypothesis": "Weekly meeting can separate genuine demand from definition noise",
              "test_method": "Standing agenda item in capacity meeting, 4 weeks",
              "outcome": "South/North pilot agenda adopted",
              "status": "Under test", "month": "M4", "linked_artefact": "demand-capacity-productivity",
              "problem": "Backlog grew in March but partly because dashboard referrals and OPT-C diverged — teams risked misreading genuine pressure.",
              "small_test": "Standing five-minute review in weekly capacity meeting: OPT-C vs dashboard referrals, long-wait count, and agreed narrative line.",
              "evidence": "Minutes show correct classification in at least three of four weeks; managers cite artefact vs pressure accurately.",
              "decision": "Agency, roster and escalation — real demand vs wait to fix definitions.",
              "next_step": "Continue through OPT-C sign-off; promote as standing agenda if managers keep using it.",
              "scale_safe_when": "Agreed definitions stable; chair rotates but format survives secondment handover."},
             {"idea_id": "IDEA-12", "idea_name": "Source-to-report walkthrough with CMHT leads",
              "hypothesis": "Lineage map helps managers without BI jargon",
              "test_method": "Two 45-minute sessions with CMHT leads",
              "outcome": "Second session scheduled",
              "status": "Under test", "month": "M4", "linked_artefact": "source-to-report-map",
              "problem": "Managers disengage from lineage documentation they cannot navigate when a figure is challenged.",
              "small_test": "Walk two CMHT leads through the interactive map using a live disputed referral example; collect what helped and what confused.",
              "evidence": "Leads can name owner and source of one KPI without BI present; feedback shapes filter presets.",
              "decision": "Whether to roll out map walkthroughs to all CMHT teams.",
              "next_step": "Complete second session; simplify preset labels from feedback.",
              "scale_safe_when": "Walkthrough guide written; BI maintains map; managers request sessions without performance lead chasing."},
             {"idea_id": "IDEA-13", "idea_name": "Handover checklist with incoming post-holder",
              "hypothesis": "Structured handover sustains deliverables after M6",
              "test_method": "Checklist review with stand-in owner in M5",
              "outcome": "Embedded in deliverables register",
              "status": "Promoted", "month": "M6", "linked_artefact": "deliverables/index",
              "problem": "Secondment outputs often live in one person’s folder and decay when they leave.",
              "small_test": "Run handover checklist in M5 with Head of Business & Performance or nominated stand-in: location, owner, last review date per deliverable.",
              "evidence": "All six deliverables have named owner and location confirmed; one gap closed before M6.",
              "decision": "Whether secondment outputs become business-as-usual products.",
              "next_step": "Promoted — checklist on deliverables index and month-six playbook step.",
              "scale_safe_when": "Incoming post-holder signs register; monthly review date set for each artefact."},
         ]),
        ("improvement_benefits_tracker.csv",
         ["benefit_id", "benefit_description", "baseline", "target", "status", "owner", "evidence", "target_month"],
         [
             {"benefit_id": "BEN-01", "benefit_description": "Agreed referral definition embedded", "baseline": "3 competing definitions", "target": "Single OPT-C signed off", "status": "Amber", "owner": "Performance lead", "evidence": "kpi-definitions-register", "target_month": "M3"},
             {"benefit_id": "BEN-02", "benefit_description": "Monthly reconciliation routine", "baseline": "Ad hoc", "target": "Scheduled pack before SLT", "status": "Green", "owner": "BI lead", "evidence": "reporting-assurance-during-migration", "target_month": "M4"},
             {"benefit_id": "BEN-03", "benefit_description": "Reporting assurance pack live", "baseline": "Three overlapping registers", "target": "Single assurance narrative with publish gate", "status": "Green", "owner": "Performance lead", "evidence": "reporting-assurance-during-migration", "target_month": "M4"},
             {"benefit_id": "BEN-04", "benefit_description": "Demand/capacity insight for CMHT", "baseline": "Spreadsheet only", "target": "Weekly pack with productivity", "status": "Green", "owner": "Service manager", "evidence": "demand-capacity-productivity", "target_month": "M4"},
             {"benefit_id": "BEN-05", "benefit_description": "Board-safe senior brief template", "baseline": "Inconsistent packs", "target": "Template with confidence column", "status": "Amber", "owner": "Performance lead", "evidence": "senior-performance-brief", "target_month": "M5"},
             {"benefit_id": "BEN-06", "benefit_description": "Migration assurance maintained", "baseline": "Tacit knowledge", "target": "Owned risks + checks + publish rules", "status": "Green", "owner": "Performance lead", "evidence": "reporting-assurance-during-migration", "target_month": "M3"},
             {"benefit_id": "BEN-07", "benefit_description": "Reusable change playbook", "baseline": "None", "target": "Documented 10-step model", "status": "Amber", "owner": "Performance lead", "evidence": "six-months-trusted-performance", "target_month": "M6"},
             {"benefit_id": "BEN-08", "benefit_description": "Handover pack complete", "baseline": "n/a", "target": "All artefacts owned and located", "status": "Amber", "owner": "Performance lead", "evidence": "deliverables/index", "target_month": "M6"},
         ]),
        ("handover_documentation_register.csv",
         ["doc_id", "document_name", "purpose", "owner", "location", "handover_status"],
         [
             {"doc_id": "DOC-01", "document_name": "KPI and definitions register", "purpose": "Agreed measure definitions", "owner": "Performance lead", "location": "deliverables/kpi-definitions-register", "handover_status": "Draft"},
             {"doc_id": "DOC-02", "document_name": "Source-to-report map", "purpose": "Lineage and sign-off points", "owner": "BI lead", "location": "deliverables/source-to-report-map", "handover_status": "Draft"},
             {"doc_id": "DOC-03", "document_name": "Reporting assurance pack", "purpose": "Risks, checks, confidence and publish decisions", "owner": "Performance lead", "location": "deliverables/reporting-assurance-during-migration", "handover_status": "Active"},
             {"doc_id": "DOC-04", "document_name": "Source-to-report map", "purpose": "Report inventory and field lineage", "owner": "BI lead", "location": "secondment/source-to-report.html", "handover_status": "Draft"},
             {"doc_id": "DOC-05", "document_name": "Validation and reconciliation SOP", "purpose": "Monthly checks before publish", "owner": "BI lead", "location": "deliverables/reporting-assurance-during-migration", "handover_status": "Draft"},
             {"doc_id": "DOC-06", "document_name": "Data dictionary", "purpose": "Field definitions for DRH demo", "owner": "BI lead", "location": "secondment-demo/data_dictionary.md", "handover_status": "Ready"},
             {"doc_id": "DOC-07", "document_name": "Change playbook", "purpose": "Reuse for next migration", "owner": "Performance lead", "location": "six-months-trusted-performance.html#reusable-approach", "handover_status": "Draft"},
             {"doc_id": "DOC-08", "document_name": "Senior brief template", "purpose": "SLT/Board narrative structure", "owner": "Performance lead", "location": "deliverables/senior-performance-brief", "handover_status": "Ready"},
         ]),
        ("change_playbook.csv",
         ["step", "month", "phase", "activity", "artefact_produced", "reuse_note"],
         [
             {"step": "1", "month": "M1", "phase": "Listen", "activity": "Map stakeholders, feeds, reports", "artefact_produced": "Source-to-report map", "reuse_note": "Start every migration here"},
             {"step": "2", "month": "M1", "phase": "Baseline", "activity": "Document current definitions and volumes", "artefact_produced": "Baseline reconciliation", "reuse_note": "Compare before/after"},
             {"step": "3", "month": "M2", "phase": "Define", "activity": "Facilitate agreed KPI definitions", "artefact_produced": "KPI definitions register", "reuse_note": "Do not skip service sign-off"},
             {"step": "4", "month": "M2", "phase": "Map", "activity": "Build source-to-report lineage", "artefact_produced": "Source-to-report map", "reuse_note": "Update when feeds change"},
             {"step": "5", "month": "M3", "phase": "Control", "activity": "Maintain reporting assurance pack", "artefact_produced": "Reporting assurance during migration", "reuse_note": "Risks, checks and publish rules together"},
             {"step": "6", "month": "M3", "phase": "Validate", "activity": "Implement validation checks", "artefact_produced": "Reporting assurance during migration", "reuse_note": "Automate where possible"},
             {"step": "7", "month": "M4", "phase": "Prototype", "activity": "Build local performance packs", "artefact_produced": "Demand/capacity pack", "reuse_note": "Test with service managers"},
             {"step": "8", "month": "M5", "phase": "Reconcile", "activity": "Monthly old vs new vs agreed", "artefact_produced": "Reconciliation outputs", "reuse_note": "Critical in phase D"},
             {"step": "9", "month": "M5", "phase": "Embed", "activity": "Apply confidence model before publish", "artefact_produced": "Reporting assurance during migration", "reuse_note": "Mark must-not-fail reports"},
             {"step": "10", "month": "M6", "phase": "Handover", "activity": "Document and transfer ownership", "artefact_produced": "Six deliverables register", "reuse_note": "Playbook becomes template for next change"},
         ]),
        ("senior_brief_sections.csv",
         ["section", "template_prompt", "mar2026_example", "confidence"],
         [
             {"section": "Bottom line", "template_prompt": "One paragraph: what matters + definition caveat",
              "mar2026_example": "March referrals appear stable on dashboard (+2%) but agreed definition shows 11% fall; separate demand pressure from definition artefact.",
              "confidence": "Low until sign-off"},
             {"section": "Headline figures", "template_prompt": "Table: measure, dashboard, agreed, confidence",
              "mar2026_example": "Referrals: 154 dashboard / 134 agreed. Backlog W21: 264.",
              "confidence": "Mixed"},
             {"section": "Risks", "template_prompt": "Top 3 migration/performance risks",
              "mar2026_example": "R002 dashboard meaning; R005 MHSDS legacy logic; workforce availability 0.82.",
              "confidence": "Medium"},
             {"section": "Recommended actions", "template_prompt": "3-5 actions with owners",
              "mar2026_example": "Definition workshop; withhold dashboard from Board; review agency spend.",
              "confidence": "High"},
         ]),
    ]

    counts: dict[str, int] = {
        "legendary_cmht_cases.csv": write_csv("legendary_cmht_cases.csv", lc_fields, legendary),
        "pathwayone_actions.csv": write_csv("pathwayone_actions.csv", act_fields, actions),
    }
    for name, fields, rows in datasets:
        counts[name] = write_csv(name, fields, rows)

    episodes = build_episodes(legendary, actions)
    map_rows = build_source_to_report_map()
    counts["fact_mh_referral_episode.csv"] = write_csv(
        "fact_mh_referral_episode.csv", list(episodes[0].keys()), episodes)
    counts["source_to_report_map.csv"] = write_csv("source_to_report_map.csv", MAP_COLS, map_rows)

    mhsds_view = [r for r in map_rows if r["report_name"] == "MHSDS-like monthly submission"]
    local_view = [r for r in map_rows if r["report_name"] == "Local demand and access performance pack"]
    counts["source_to_report_map_mhsds_view.csv"] = write_csv(
        "source_to_report_map_mhsds_view.csv", MAP_COLS, mhsds_view)
    counts["source_to_report_map_local_demand_view.csv"] = write_csv(
        "source_to_report_map_local_demand_view.csv", MAP_COLS, local_view)

    for fname, (fields, rows) in build_submission_artifacts(episodes).items():
        counts[fname] = write_csv(fname, fields, rows)

    page_map = {
        "legendary_cmht_cases.csv": "secondment/definition-migration.html",
        "pathwayone_actions.csv": "secondment/definition-migration.html",
        "reconciliation_monthly.csv": "secondment/deliverables/reporting-assurance-during-migration.html",
        "reconciliation_detail_mar2026.csv": "secondment/deliverables/reporting-assurance-during-migration.html",
        "definition_options_referral.csv": "secondment/definition-migration.html",
        "migration_risk_register.csv": "secondment/deliverables/reporting-assurance-during-migration.html",
        "feed_cutover_log.csv": "secondment/migration-scenario.html",
        "kpi_definitions_register.csv": "secondment/deliverables/kpi-definitions-register.html",
        "source_to_report_map.csv": "secondment/source-to-report.html",
        "source_to_report_map_mhsds_view.csv": "secondment/reports/mhsds-like-submission.html",
        "source_to_report_map_local_demand_view.csv": "secondment/reports/local-demand-capacity-pack.html",
        "fact_mh_referral_episode.csv": "secondment/reports/mhsds-like-submission.html",
        "mhsds_like_submission_monthly.csv": "secondment/reports/mhsds-like-submission.html",
        "mhsds_like_submission_fields.csv": "secondment/reports/mhsds-like-submission.html",
        "mhsds_like_validation_checks.csv": "secondment/reports/mhsds-like-submission.html",
        "mhsds_like_reconciliation_summary.csv": "secondment/reports/mhsds-like-submission.html",
        "definition_decision_log.csv": "secondment/definition-migration.html",
        "local_demand_access_pack_metrics.csv": "secondment/reports/local-demand-capacity-pack.html",
        "reporting_requirements_map.csv": "secondment/deliverables/source-to-report-map.html",
        "report_catalogue.csv": "secondment/deliverables/source-to-report-map.html",
        "validation_checks_register.csv": "secondment/deliverables/reporting-assurance-during-migration.html",
        "reporting_confidence_register.csv": "secondment/deliverables/reporting-assurance-during-migration.html",
        "demand_capacity_weekly.csv": "secondment/deliverables/demand-capacity-productivity.html",
        "productivity_by_team.csv": "secondment/deliverables/demand-capacity-productivity.html",
        "demand_capacity_insights.csv": "secondment/deliverables/demand-capacity-productivity.html",
        "ideas_under_test_register.csv": "secondment/deliverables/ideas-under-test.html",
        "improvement_benefits_tracker.csv": "secondment/deliverables/index.html",
        "handover_documentation_register.csv": "secondment/deliverables/index.html",
        "change_playbook.csv": "six-months-trusted-performance.html#reusable-approach",
        "senior_brief_sections.csv": "secondment/deliverables/senior-performance-brief.html",
    }
    default_page = "secondment/deliverables/index.html"
    manifest_rows = []
    for name, n in counts.items():
        manifest_rows.append({
            "file_name": name,
            "grain": name.replace(".csv", ""),
            "row_count": str(n),
            "date_from": "2025-09",
            "date_to": "2026-05",
            "source_system": "DRH synthetic",
            "migration_phase": "A-F",
            "primary_key": name.split(".")[0],
            "linked_html_page": page_map.get(name, default_page),
            "regenerate_command": REGENERATE_CMD,
        })
    write_csv("data_manifest.csv",
              ["file_name", "grain", "row_count", "date_from", "date_to", "source_system",
               "migration_phase", "primary_key", "linked_html_page", "regenerate_command"],
              manifest_rows)
    print(f"Generated {len(counts) + 1} files in {DATA_DIR}")


if __name__ == "__main__":
    main()
